name: Build

on: [push]

jobs:
  build:
    runs-on: $${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ['1.8']

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Set up JDK
      uses: actions/setup-java@master
      with:
        java-version: ${{ matrix.java }}
        architecture: x64

    - name: Build
      run: ./gradlew build
