name: Release

on:
  push:
    branches:
      - master
   
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-java@v1.1.0
        with:
          java-version: 1.8
          
      - name: Build
        id: run_build
        run: |
          gradlew build
          echo ::set-output name=version::$(./gradlew properties -q | grep "^version:" | awk '{print $2}' | awk -F'-' '{print $1}')
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
          
      - name: Upload Zip
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./build/distributions/pipeline-setup-$${ steps.run_build.outputs.version }}.zip
          asset_name: pipeline-setup-$${ steps.run_build.outputs.version }}.zip
          asset_content_type: application/zip
      
      - name: Upload Tar
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./build/distributions/pipeline-setup-$${ steps.run_build.outputs.version }}.tar
          asset_name: pipeline-setup-$${ steps.run_build.outputs.version }}.tar
          asset_content_type: application/x-tar
      
